// pysys-challenge-web/src/components/RegistrationComponent.vue
<template>
  <div class="container">
    <header>
      <h1>PySys ERP Web Console</h1>
    </header>
    <div id="container_demo">
      <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
      <div id="wrapper">
        <div id="login" class="animate form">
          <form id="registrationForm">
            <h1> Sign up </h1>
            <p>
              <label for="usernamesignup" class="uname" data-icon="u">Your username</label>
              <input id="usernamesignup" name="usernamesignup" required="required" type="text"
                     placeholder="mysuperusername690"/>
            </p>
            <p>
              <label for="emailsignup" class="youmail" data-icon="e"> Your email</label>
              <input id="emailsignup" name="emailsignup" required="required" type="email" placeholder="mysupermail@mail.com"/>
            </p>
            <p>
              <label for="passwordsignup" class="youpasswd" data-icon="p">Your password </label>
              <input id="passwordsignup" name="passwordsignup" required="required" type="password"
                     placeholder="eg. X8df!90EO"/>
            </p>
            <p>
              <label for="passwordsignup_confirm" class="youpasswd" data-icon="p">Please confirm your password </label>
              <input id="passwordsignup_confirm" name="passwordsignup_confirm" required="required" type="password"
                     placeholder="eg. X8df!90EO"/>
            </p>
            <p class="signin button">
              <input type="submit" value="Sign up"/>
            </p>
            <p class="change_link">
              Already a member ?
              <a href="#login" class="to_register">Join us</a>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'RegistrationComponent'
}
</script>

<style scoped>

</style>

// pysys-challenge-web/src/app/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';

import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';

import { Person } from './services/interfaces/person';
import { RegistrationService } from './services/registration.service';

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent implements OnInit {

  registrationGroup: FormGroup;
  person: Person;

  constructor(
    private formBuilder: FormBuilder,
    private registrationService: RegistrationService
  ) { }

  ngOnInit(): void {
    this.registrationGroup = this.formBuilder.group({
      name: ['', [
          Validators.required,
          Validators.maxLength(12),
        ]
      ],
      username: ['', []],
      email: ['', []],
      password: ['', []],
      confirm_password: ['', []]
    });
  }
  ngOnSubmit(): void {
  }
}

<div class="container">
  <header>
    <h1>PySys ERP Web Console</h1>
  </header>
  <div id="container_demo">
    <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
    <div id="wrapper">
      <div id="login" class="animate form">
        <form name="registrationForm" [formGroup]="registrationGroup" (ngSubmit)="ngOnSubmit()">
          <h1> Registro </h1>
          <p>
            <label for="name" class="name" data-icon="u" > Nome </label>
            <input id="name" name="name" formControlName="name" type="text" placeholder="eg. John Doe"/>
          </p>
          <p>
            <label for="username" class="uname" data-icon="u" >Usu&aacute;rio</label>
            <input id="username" formControlName="username" type="text" placeholder="eg. johndoe69"/>
          </p>
          <p>
            <label for="email" class="youmail" data-icon="e">E-mail</label>
            <input id="email" formControlName="email" type="email" placeholder="eg. johndoe69@mail.com"/>
          </p>
          <p>
            <label for="password" class="youpasswd" data-icon="p" >Password</label>
            <input id="password" formControlName="password" type="password" placeholder="eg. X8df!90EO"/>
          </p>
          <p>
            <label for="confirm_password" class="youpasswd" data-icon="p" >Confirme o password</label>
            <input id="confirm_password" formControlName="confirm_password" type="password" placeholder="eg. X8df!90EO"/>
          </p>
          <p class="signin button">
            <input id="submit" type="submit" value="Registrar"/>
          </p>
          <p class="change_link">
            J&aacute; &eacute; membro ?
            <a [routerLink]="'/login'" class="to_register">Acessar agora</a>
          </p>
        </form>
      </div>
    </div>
  </div>
</div>
